---
- name: Pull docker image of DevOps_calc
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Pull DevOps Image
      docker_image:
              name: grimscorcher/devops_calc:latest
        source: pull 
